# seed_urls.py
# This file just stores the list of seed URLs for the crawler.

SEED_URLS = [
    
    "https://tu.edu.np/",
    "https://ku.edu.np/",
    "https://purbanchaluniversity.edu.np/",
    "https://pu.edu.np/",
    "https://www.fwu.edu.np/",
    "https://www.mwu.edu.np/",
    "https://rju.edu.np/",
    "https://www.uon.edu.np/",
    "https://nou.edu.np/",
    "https://afu.edu.np/",
    "https://www.mbust.edu.np/",
    "https://nsu.edu.np/",
    "https://lbu.edu.np/",
    "https://www.mtu.edu.np/",
    "https://www.gandakiuniversity.edu.np/",
    "https://mau.edu.np/",
    "https://ltu.edu.np/",
    "https://bagmatiuniversity.edu.np/",
    "https://nams.edu.np/en",
    "https://www.bpkihs.edu/",
    "https://web.pahs.edu.np/",
    "https://kahs.edu.np/",
    # "https://en.wikipedia.org/wiki/Pokhara_Academy_of_Health_Sciences",
    # "https://en.wikipedia.org/wiki/Rapti_Academy_of_Health_Sciences",
    # "https://en.wikipedia.org/wiki/Madan_Bhandari_Academy_of_Health_Sciences",
    # "https://en.wikipedia.org/wiki/Madhesh_Institute_of_Health_Sciences",
    # "https://en.wikipedia.org/wiki/List_of_forestry_colleges_in_Nepal",
    # "https://en.wikipedia.org/wiki/List_of_engineering_colleges_in_Nepal",
    # "https://en.wikipedia.org/wiki/List_of_medical_colleges_in_Nepal",
    # "https://en.wikipedia.org/wiki/Education_in_Nepal",
    "https://edusanjal.com/college/",
    "https://ctevt.org.np/",
    "https://neb.gov.np/contact-us",
    "https://moest.gov.np/",
    "https://ugcnepal.edu.np/",
    "http://www.doe.gov.np/",
]
